
// Code generated by tools/gen_shims. DO NOT EDIT.

package cachedvfs

import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/vfs"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/vfs/cachedvfs"
import _ "unsafe"

type FS = cachedvfs.FS
//go:linkname From github.com/i2y/ramune/internal/rslint/tsgo_pinned/vfs/cachedvfs.From
func From(fs vfs.FS) *cachedvfs.FS
