// Code generated by tools/gen_shims. DO NOT EDIT.

package bundled

import "github.com/i2y/ramune/internal/tsgo/bundled"
import "github.com/i2y/ramune/internal/tsgo/vfs"
import _ "unsafe"

const Embedded = bundled.Embedded

//go:linkname IsBundled github.com/i2y/ramune/internal/tsgo/bundled.IsBundled
func IsBundled(path string) bool

var LibNames = bundled.LibNames

//go:linkname LibPath github.com/i2y/ramune/internal/tsgo/bundled.LibPath
func LibPath() string

//go:linkname TestingLibPath github.com/i2y/ramune/internal/tsgo/bundled.TestingLibPath
func TestingLibPath() string

//go:linkname WrapFS github.com/i2y/ramune/internal/tsgo/bundled.WrapFS
func WrapFS(fs vfs.FS) vfs.FS
