package rules

import (
	"github.com/i2y/ramune/internal/rslint/rule"
	"github.com/i2y/ramune/internal/rslint/rules/accessor_pairs"
	"github.com/i2y/ramune/internal/rslint/rules/array_callback_return"
	"github.com/i2y/ramune/internal/rslint/rules/arrow_body_style"
	"github.com/i2y/ramune/internal/rslint/rules/complexity"
	"github.com/i2y/ramune/internal/rslint/rules/constructor_super"
	"github.com/i2y/ramune/internal/rslint/rules/curly"
	"github.com/i2y/ramune/internal/rslint/rules/default_case"
	"github.com/i2y/ramune/internal/rslint/rules/default_case_last"
	"github.com/i2y/ramune/internal/rslint/rules/eqeqeq"
	"github.com/i2y/ramune/internal/rslint/rules/for_direction"
	"github.com/i2y/ramune/internal/rslint/rules/getter_return"
	"github.com/i2y/ramune/internal/rslint/rules/guard_for_in"
	"github.com/i2y/ramune/internal/rslint/rules/max_depth"
	"github.com/i2y/ramune/internal/rslint/rules/max_lines"
	"github.com/i2y/ramune/internal/rslint/rules/max_lines_per_function"
	"github.com/i2y/ramune/internal/rslint/rules/max_nested_callbacks"
	"github.com/i2y/ramune/internal/rslint/rules/max_params"
	"github.com/i2y/ramune/internal/rslint/rules/no_alert"
	"github.com/i2y/ramune/internal/rslint/rules/no_async_promise_executor"
	"github.com/i2y/ramune/internal/rslint/rules/no_await_in_loop"
	"github.com/i2y/ramune/internal/rslint/rules/no_bitwise"
	"github.com/i2y/ramune/internal/rslint/rules/no_caller"
	"github.com/i2y/ramune/internal/rslint/rules/no_case_declarations"
	"github.com/i2y/ramune/internal/rslint/rules/no_class_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_compare_neg_zero"
	"github.com/i2y/ramune/internal/rslint/rules/no_cond_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_console"
	"github.com/i2y/ramune/internal/rslint/rules/no_const_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_constant_binary_expression"
	"github.com/i2y/ramune/internal/rslint/rules/no_constant_condition"
	"github.com/i2y/ramune/internal/rslint/rules/no_constructor_return"
	"github.com/i2y/ramune/internal/rslint/rules/no_control_regex"
	"github.com/i2y/ramune/internal/rslint/rules/no_debugger"
	"github.com/i2y/ramune/internal/rslint/rules/no_delete_var"
	"github.com/i2y/ramune/internal/rslint/rules/no_dupe_args"
	"github.com/i2y/ramune/internal/rslint/rules/no_dupe_class_members"
	"github.com/i2y/ramune/internal/rslint/rules/no_dupe_else_if"
	"github.com/i2y/ramune/internal/rslint/rules/no_dupe_keys"
	"github.com/i2y/ramune/internal/rslint/rules/no_duplicate_case"
	"github.com/i2y/ramune/internal/rslint/rules/no_duplicate_imports"
	"github.com/i2y/ramune/internal/rslint/rules/no_else_return"
	"github.com/i2y/ramune/internal/rslint/rules/no_empty"
	"github.com/i2y/ramune/internal/rslint/rules/no_empty_character_class"
	"github.com/i2y/ramune/internal/rslint/rules/no_empty_function"
	"github.com/i2y/ramune/internal/rslint/rules/no_empty_pattern"
	"github.com/i2y/ramune/internal/rslint/rules/no_empty_static_block"
	"github.com/i2y/ramune/internal/rslint/rules/no_eval"
	"github.com/i2y/ramune/internal/rslint/rules/no_ex_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_extend_native"
	"github.com/i2y/ramune/internal/rslint/rules/no_extra_bind"
	"github.com/i2y/ramune/internal/rslint/rules/no_extra_boolean_cast"
	"github.com/i2y/ramune/internal/rslint/rules/no_extra_label"
	"github.com/i2y/ramune/internal/rslint/rules/no_fallthrough"
	"github.com/i2y/ramune/internal/rslint/rules/no_func_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_global_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_implicit_coercion"
	"github.com/i2y/ramune/internal/rslint/rules/no_implied_eval"
	"github.com/i2y/ramune/internal/rslint/rules/no_import_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_inner_declarations"
	"github.com/i2y/ramune/internal/rslint/rules/no_invalid_regexp"
	"github.com/i2y/ramune/internal/rslint/rules/no_irregular_whitespace"
	"github.com/i2y/ramune/internal/rslint/rules/no_iterator"
	"github.com/i2y/ramune/internal/rslint/rules/no_label_var"
	"github.com/i2y/ramune/internal/rslint/rules/no_labels"
	"github.com/i2y/ramune/internal/rslint/rules/no_lone_blocks"
	"github.com/i2y/ramune/internal/rslint/rules/no_loop_func"
	"github.com/i2y/ramune/internal/rslint/rules/no_loss_of_precision"
	"github.com/i2y/ramune/internal/rslint/rules/no_misleading_character_class"
	"github.com/i2y/ramune/internal/rslint/rules/no_multi_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_multi_str"
	"github.com/i2y/ramune/internal/rslint/rules/no_nested_ternary"
	"github.com/i2y/ramune/internal/rslint/rules/no_new"
	"github.com/i2y/ramune/internal/rslint/rules/no_new_func"
	"github.com/i2y/ramune/internal/rslint/rules/no_new_native_nonconstructor"
	"github.com/i2y/ramune/internal/rslint/rules/no_new_object"
	"github.com/i2y/ramune/internal/rslint/rules/no_new_symbol"
	"github.com/i2y/ramune/internal/rslint/rules/no_new_wrappers"
	"github.com/i2y/ramune/internal/rslint/rules/no_nonoctal_decimal_escape"
	"github.com/i2y/ramune/internal/rslint/rules/no_obj_calls"
	"github.com/i2y/ramune/internal/rslint/rules/no_octal"
	"github.com/i2y/ramune/internal/rslint/rules/no_octal_escape"
	"github.com/i2y/ramune/internal/rslint/rules/no_param_reassign"
	"github.com/i2y/ramune/internal/rslint/rules/no_proto"
	"github.com/i2y/ramune/internal/rslint/rules/no_prototype_builtins"
	"github.com/i2y/ramune/internal/rslint/rules/no_redeclare"
	"github.com/i2y/ramune/internal/rslint/rules/no_regex_spaces"
	"github.com/i2y/ramune/internal/rslint/rules/no_restricted_imports"
	"github.com/i2y/ramune/internal/rslint/rules/no_restricted_syntax"
	"github.com/i2y/ramune/internal/rslint/rules/no_return_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_script_url"
	"github.com/i2y/ramune/internal/rslint/rules/no_self_assign"
	"github.com/i2y/ramune/internal/rslint/rules/no_self_compare"
	"github.com/i2y/ramune/internal/rslint/rules/no_sequences"
	"github.com/i2y/ramune/internal/rslint/rules/no_setter_return"
	"github.com/i2y/ramune/internal/rslint/rules/no_shadow"
	"github.com/i2y/ramune/internal/rslint/rules/no_shadow_restricted_names"
	"github.com/i2y/ramune/internal/rslint/rules/no_sparse_arrays"
	"github.com/i2y/ramune/internal/rslint/rules/no_template_curly_in_string"
	"github.com/i2y/ramune/internal/rslint/rules/no_this_before_super"
	"github.com/i2y/ramune/internal/rslint/rules/no_throw_literal"
	"github.com/i2y/ramune/internal/rslint/rules/no_unassigned_vars"
	"github.com/i2y/ramune/internal/rslint/rules/no_undef"
	"github.com/i2y/ramune/internal/rslint/rules/no_undef_init"
	"github.com/i2y/ramune/internal/rslint/rules/no_unexpected_multiline"
	"github.com/i2y/ramune/internal/rslint/rules/no_unmodified_loop_condition"
	"github.com/i2y/ramune/internal/rslint/rules/no_unneeded_ternary"
	"github.com/i2y/ramune/internal/rslint/rules/no_unreachable"
	"github.com/i2y/ramune/internal/rslint/rules/no_unsafe_finally"
	"github.com/i2y/ramune/internal/rslint/rules/no_unsafe_negation"
	"github.com/i2y/ramune/internal/rslint/rules/no_unsafe_optional_chaining"
	"github.com/i2y/ramune/internal/rslint/rules/no_unused_expressions"
	"github.com/i2y/ramune/internal/rslint/rules/no_unused_labels"
	"github.com/i2y/ramune/internal/rslint/rules/no_unused_private_class_members"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_backreference"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_call"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_catch"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_computed_key"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_concat"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_constructor"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_escape"
	"github.com/i2y/ramune/internal/rslint/rules/no_useless_rename"
	"github.com/i2y/ramune/internal/rslint/rules/no_var"
	"github.com/i2y/ramune/internal/rslint/rules/no_with"
	"github.com/i2y/ramune/internal/rslint/rules/object_shorthand"
	"github.com/i2y/ramune/internal/rslint/rules/one_var"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_arrow_callback"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_const"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_exponentiation_operator"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_numeric_literals"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_promise_reject_errors"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_regex_literals"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_rest_params"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_spread"
	"github.com/i2y/ramune/internal/rslint/rules/prefer_template"
	"github.com/i2y/ramune/internal/rslint/rules/radix"
	"github.com/i2y/ramune/internal/rslint/rules/require_atomic_updates"
	"github.com/i2y/ramune/internal/rslint/rules/require_await"
	"github.com/i2y/ramune/internal/rslint/rules/require_yield"
	"github.com/i2y/ramune/internal/rslint/rules/strict"
	"github.com/i2y/ramune/internal/rslint/rules/symbol_description"
	"github.com/i2y/ramune/internal/rslint/rules/use_isnan"
	"github.com/i2y/ramune/internal/rslint/rules/valid_typeof"
)

func GetAllRules() []rule.Rule {
	return []rule.Rule{
		accessor_pairs.AccessorPairsRule,
		array_callback_return.ArrayCallbackReturnRule,
		arrow_body_style.ArrowBodyStyleRule,
		complexity.ComplexityRule,
		constructor_super.ConstructorSuperRule,
		curly.CurlyRule,
		default_case.DefaultCaseRule,
		default_case_last.DefaultCaseLastRule,
		for_direction.ForDirectionRule,
		getter_return.GetterReturnRule,
		guard_for_in.GuardForInRule,
		max_depth.MaxDepthRule,
		max_lines.MaxLinesRule,
		max_lines_per_function.MaxLinesPerFunctionRule,
		max_nested_callbacks.MaxNestedCallbacksRule,
		max_params.MaxParamsRule,
		no_alert.NoAlertRule,
		no_async_promise_executor.NoAsyncPromiseExecutorRule,
		no_await_in_loop.NoAwaitInLoopRule,
		no_bitwise.NoBitwiseRule,
		no_caller.NoCallerRule,
		no_case_declarations.NoCaseDeclarationsRule,
		no_class_assign.NoClassAssignRule,
		no_compare_neg_zero.NoCompareNegZeroRule,
		no_cond_assign.NoCondAssignRule,
		no_console.NoConsoleRule,
		no_const_assign.NoConstAssignRule,
		no_constant_binary_expression.NoConstantBinaryExpressionRule,
		no_constant_condition.NoConstantConditionRule,
		no_constructor_return.NoConstructorReturnRule,
		no_control_regex.NoControlRegexRule,
		no_debugger.NoDebuggerRule,
		no_delete_var.NoDeleteVarRule,
		no_dupe_args.NoDupeArgsRule,
		no_dupe_class_members.NoDupeClassMembersRule,
		no_dupe_keys.NoDupeKeysRule,
		no_duplicate_case.NoDuplicateCaseRule,
		no_duplicate_imports.NoDuplicateImportsRule,
		no_else_return.NoElseReturnRule,
		no_empty.NoEmptyRule,
		no_empty_function.NoEmptyFunctionRule,
		no_empty_pattern.NoEmptyPatternRule,
		no_empty_static_block.NoEmptyStaticBlockRule,
		no_eval.NoEvalRule,
		no_ex_assign.NoExAssignRule,
		no_extend_native.NoExtendNativeRule,
		no_extra_bind.NoExtraBindRule,
		no_extra_label.NoExtraLabelRule,
		no_label_var.NoLabelVarRule,
		no_labels.NoLabelsRule,
		no_func_assign.NoFuncAssignRule,
		no_global_assign.NoGlobalAssignRule,
		no_implicit_coercion.NoImplicitCoercionRule,
		no_implied_eval.NoImpliedEvalRule,
		no_import_assign.NoImportAssignRule,
		no_inner_declarations.NoInnerDeclarationsRule,
		no_irregular_whitespace.NoIrregularWhitespaceRule,
		no_lone_blocks.NoLoneBlocksRule,
		no_loop_func.NoLoopFuncRule,
		no_loss_of_precision.NoLossOfPrecisionRule,
		no_misleading_character_class.NoMisleadingCharacterClassRule,
		no_new.NoNewRule,
		no_new_func.NoNewFuncRule,
		no_new_native_nonconstructor.NoNewNativeNonconstructorRule,
		no_new_wrappers.NoNewWrappersRule,
		no_restricted_imports.NoRestrictedImportsRule,
		no_restricted_syntax.NoRestrictedSyntaxRule,
		no_multi_assign.NoMultiAssignRule,
		no_multi_str.NoMultiStrRule,
		no_nested_ternary.NoNestedTernaryRule,
		no_nonoctal_decimal_escape.NoNonoctalDecimalEscapeRule,
		no_octal.NoOctalRule,
		no_octal_escape.NoOctalEscapeRule,
		no_param_reassign.NoParamReassignRule,
		no_proto.NoProtoRule,
		no_redeclare.NoRedeclareRule,
		radix.RadixRule,
		no_regex_spaces.NoRegexSpacesRule,
		no_return_assign.NoReturnAssignRule,
		no_script_url.NoScriptUrlRule,
		no_self_assign.NoSelfAssignRule,
		no_self_compare.NoSelfCompareRule,
		no_sequences.NoSequencesRule,
		no_shadow.NoShadowRule,
		no_shadow_restricted_names.NoShadowRestrictedNamesRule,
		strict.StrictRule,
		no_template_curly_in_string.NoTemplateCurlyInStringRule,
		no_useless_computed_key.NoUselessComputedKeyRule,
		no_useless_concat.NoUselessConcatRule,
		no_sparse_arrays.NoSparseArraysRule,
		no_extra_boolean_cast.NoExtraBooleanCastRule,
		no_unneeded_ternary.NoUnneededTernaryRule,
		no_undef.NoUndefRule,
		no_undef_init.NoUndefInitRule,
		no_unassigned_vars.NoUnassignedVarsRule,
		prefer_const.PreferConstRule,
		prefer_exponentiation_operator.PreferExponentiationOperatorRule,
		prefer_numeric_literals.PreferNumericLiteralsRule,
		prefer_promise_reject_errors.PreferPromiseRejectErrorsRule,
		prefer_regex_literals.PreferRegexLiteralsRule,
		prefer_template.PreferTemplateRule,
		no_this_before_super.NoThisBeforeSuperRule,
		no_var.NoVarRule,
		no_with.NoWithRule,
		prefer_rest_params.PreferRestParamsRule,
		prefer_spread.PreferSpreadRule,
		no_empty_character_class.NoEmptyCharacterClassRule,
		no_invalid_regexp.NoInvalidRegexpRule,
		no_iterator.NoIteratorRule,
		no_setter_return.NoSetterReturnRule,
		no_unsafe_negation.NoUnsafeNegationRule,
		no_obj_calls.NoObjCallsRule,
		no_new_object.NoNewObjectRule,
		no_new_symbol.NoNewSymbolRule,
		use_isnan.UseIsNaNRule,
		eqeqeq.EqeqeqRule,
		no_fallthrough.NoFallthroughRule,
		valid_typeof.ValidTypeofRule,
		no_unsafe_optional_chaining.NoUnsafeOptionalChainingRule,
		no_unsafe_finally.NoUnsafeFinallyRule,
		no_unmodified_loop_condition.NoUnmodifiedLoopConditionRule,
		no_unreachable.NoUnreachableRule,
		require_atomic_updates.RequireAtomicUpdatesRule,
		object_shorthand.ObjectShorthandRule,
		no_unused_expressions.NoUnusedExpressionsRule,
		no_unused_labels.NoUnusedLabelsRule,
		no_unused_private_class_members.NoUnusedPrivateClassMembersRule,
		one_var.OneVarRule,
		prefer_arrow_callback.PreferArrowCallbackRule,
		no_dupe_else_if.NoDupeElseIfRule,
		no_throw_literal.NoThrowLiteralRule,
		no_useless_backreference.NoUselessBackreferenceRule,
		no_useless_call.NoUselessCallRule,
		no_useless_catch.NoUselessCatchRule,
		no_useless_escape.NoUselessEscapeRule,
		no_useless_rename.NoUselessRenameRule,
		no_useless_constructor.NoUselessConstructorRule,
		no_prototype_builtins.NoPrototypeBuiltinsRule,
		require_await.RequireAwaitRule,
		require_yield.RequireYieldRule,
		symbol_description.SymbolDescriptionRule,
		no_unexpected_multiline.NoUnexpectedMultilineRule,
	}
}
