// Code generated by tools/gen_shims. DO NOT EDIT.

package osvfs

import "github.com/i2y/ramune/internal/tsgo/vfs"
import _ "github.com/i2y/ramune/internal/tsgo/vfs/osvfs"
import _ "unsafe"

//go:linkname FS github.com/i2y/ramune/internal/tsgo/vfs/osvfs.FS
func FS() vfs.FS

//go:linkname GetGlobalTypingsCacheLocation github.com/i2y/ramune/internal/tsgo/vfs/osvfs.GetGlobalTypingsCacheLocation
func GetGlobalTypingsCacheLocation() string
