// Code generated by tools/gen_shims. DO NOT EDIT.

package compiler

import "context"
import "github.com/i2y/ramune/internal/tsgo/ast"
import "github.com/i2y/ramune/internal/tsgo/compiler"
import "github.com/i2y/ramune/internal/tsgo/core"
import "github.com/i2y/ramune/internal/tsgo/diagnostics"
import "github.com/i2y/ramune/internal/tsgo/tsoptions"
import "github.com/i2y/ramune/internal/tsgo/vfs"
import _ "unsafe"

type CheckerPool = compiler.CheckerPool

//go:linkname CombineEmitResults github.com/i2y/ramune/internal/tsgo/compiler.CombineEmitResults
func CombineEmitResults(results []*compiler.EmitResult) *compiler.EmitResult

type CompilerHost = compiler.CompilerHost

const EmitAll = compiler.EmitAll

type EmitHost = compiler.EmitHost
type EmitOnly = compiler.EmitOnly

const EmitOnlyDts = compiler.EmitOnlyDts
const EmitOnlyForcedDts = compiler.EmitOnlyForcedDts
const EmitOnlyJs = compiler.EmitOnlyJs

type EmitOptions = compiler.EmitOptions
type EmitResult = compiler.EmitResult
type FileIncludeReason = compiler.FileIncludeReason

//go:linkname FilterNoEmitSemanticDiagnostics github.com/i2y/ramune/internal/tsgo/compiler.FilterNoEmitSemanticDiagnostics
func FilterNoEmitSemanticDiagnostics(diagnostics []*ast.Diagnostic, options *core.CompilerOptions) []*ast.Diagnostic

//go:linkname GetDiagnosticsOfAnyProgram github.com/i2y/ramune/internal/tsgo/compiler.GetDiagnosticsOfAnyProgram
func GetDiagnosticsOfAnyProgram(ctx context.Context, program compiler.ProgramLike, file *ast.SourceFile, skipNoEmitCheckForDtsDiagnostics bool, getBindDiagnostics func(context.Context, *ast.SourceFile) []*ast.Diagnostic, getSemanticDiagnostics func(context.Context, *ast.SourceFile) []*ast.Diagnostic) []*ast.Diagnostic

//go:linkname HandleNoEmitOnError github.com/i2y/ramune/internal/tsgo/compiler.HandleNoEmitOnError
func HandleNoEmitOnError(ctx context.Context, program compiler.ProgramLike, file *ast.SourceFile) *compiler.EmitResult

type LibFile = compiler.LibFile

//go:linkname NewCachedFSCompilerHost github.com/i2y/ramune/internal/tsgo/compiler.NewCachedFSCompilerHost
func NewCachedFSCompilerHost(currentDirectory string, fs vfs.FS, defaultLibraryPath string, extendedConfigCache tsoptions.ExtendedConfigCache, trace func(msg *diagnostics.Message, args ...any)) compiler.CompilerHost

//go:linkname NewCompilerHost github.com/i2y/ramune/internal/tsgo/compiler.NewCompilerHost
func NewCompilerHost(currentDirectory string, fs vfs.FS, defaultLibraryPath string, extendedConfigCache tsoptions.ExtendedConfigCache, trace func(msg *diagnostics.Message, args ...any)) compiler.CompilerHost

//go:linkname NewProgram github.com/i2y/ramune/internal/tsgo/compiler.NewProgram
func NewProgram(opts compiler.ProgramOptions) *compiler.Program

type Program = compiler.Program
type ProgramLike = compiler.ProgramLike
type ProgramOptions = compiler.ProgramOptions

//go:linkname SortAndDeduplicateDiagnostics github.com/i2y/ramune/internal/tsgo/compiler.SortAndDeduplicateDiagnostics
func SortAndDeduplicateDiagnostics(diagnostics []*ast.Diagnostic) []*ast.Diagnostic

type SourceFileMayBeEmittedHost = compiler.SourceFileMayBeEmittedHost
type SourceMapEmitResult = compiler.SourceMapEmitResult
type WriteFile = compiler.WriteFile
type WriteFileData = compiler.WriteFileData
