
// Code generated by tools/gen_shims. DO NOT EDIT.

package tsoptions

import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/ast"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/collections"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/core"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/diagnostics"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions"
import "github.com/i2y/ramune/internal/rslint/tsgo_pinned/tspath"
import "reflect"
import _ "unsafe"

type AlternateModeDiagnostics = tsoptions.AlternateModeDiagnostics
var BuildNameMap = tsoptions.BuildNameMap
var BuildOpts = tsoptions.BuildOpts
var CommandLineCompilerOptionsMap = tsoptions.CommandLineCompilerOptionsMap
type CommandLineOption = tsoptions.CommandLineOption
type CommandLineOptionKind = tsoptions.CommandLineOptionKind
type CommandLineOptionNameMap = tsoptions.CommandLineOptionNameMap
const CommandLineOptionTypeBoolean = tsoptions.CommandLineOptionTypeBoolean
const CommandLineOptionTypeEnum = tsoptions.CommandLineOptionTypeEnum
const CommandLineOptionTypeList = tsoptions.CommandLineOptionTypeList
const CommandLineOptionTypeListOrElement = tsoptions.CommandLineOptionTypeListOrElement
const CommandLineOptionTypeNumber = tsoptions.CommandLineOptionTypeNumber
const CommandLineOptionTypeObject = tsoptions.CommandLineOptionTypeObject
const CommandLineOptionTypeString = tsoptions.CommandLineOptionTypeString
var CompilerNameMap = tsoptions.CompilerNameMap
//go:linkname CompilerOptionsAffectDeclarationPath github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CompilerOptionsAffectDeclarationPath
func CompilerOptionsAffectDeclarationPath(oldOptions *core.CompilerOptions, newOptions *core.CompilerOptions) bool
//go:linkname CompilerOptionsAffectEmit github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CompilerOptionsAffectEmit
func CompilerOptionsAffectEmit(oldOptions *core.CompilerOptions, newOptions *core.CompilerOptions) bool
//go:linkname CompilerOptionsAffectSemanticDiagnostics github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CompilerOptionsAffectSemanticDiagnostics
func CompilerOptionsAffectSemanticDiagnostics(oldOptions *core.CompilerOptions, newOptions *core.CompilerOptions) bool
var CompilerOptionsDidYouMeanDiagnostics = tsoptions.CompilerOptionsDidYouMeanDiagnostics
type CompilerOptionsValue = tsoptions.CompilerOptionsValue
//go:linkname ConvertOptionToAbsolutePath github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ConvertOptionToAbsolutePath
func ConvertOptionToAbsolutePath(o string, v any, optionMap tsoptions.CommandLineOptionNameMap, cwd string) (any, bool)
//go:linkname CreateDiagnosticAtReferenceSyntax github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CreateDiagnosticAtReferenceSyntax
func CreateDiagnosticAtReferenceSyntax(config *tsoptions.ParsedCommandLine, index int, message *diagnostics.Message, args ...any) *ast.Diagnostic
//go:linkname CreateDiagnosticForNodeInSourceFile github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CreateDiagnosticForNodeInSourceFile
func CreateDiagnosticForNodeInSourceFile(sourceFile *ast.SourceFile, node *ast.Node, message *diagnostics.Message, args ...any) *ast.Diagnostic
//go:linkname CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic
func CreateDiagnosticForNodeInSourceFileOrCompilerDiagnostic(sourceFile *ast.SourceFile, node *ast.Node, message *diagnostics.Message, args ...any) *ast.Diagnostic
type DidYouMeanOptionsDiagnostics = tsoptions.DidYouMeanOptionsDiagnostics
type ExtendedConfigCache = tsoptions.ExtendedConfigCache
type ExtendedConfigCacheEntry = tsoptions.ExtendedConfigCacheEntry
type FileExtensionInfo = tsoptions.FileExtensionInfo
//go:linkname ForEachCompilerOptionValue github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ForEachCompilerOptionValue
func ForEachCompilerOptionValue(options *core.CompilerOptions, declFilter func(*tsoptions.CommandLineOption) bool, fn func(option *tsoptions.CommandLineOption, value reflect.Value, i int) bool) bool
//go:linkname GetCallbackForFindingPropertyAssignmentByValue github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetCallbackForFindingPropertyAssignmentByValue
func GetCallbackForFindingPropertyAssignmentByValue(value string) func(property *ast.PropertyAssignment) *ast.Node
//go:linkname GetDefaultLibFileName github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetDefaultLibFileName
func GetDefaultLibFileName(options *core.CompilerOptions) string
//go:linkname GetLibFileName github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetLibFileName
func GetLibFileName(libName string) (string, bool)
//go:linkname GetNameMapFromList github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetNameMapFromList
func GetNameMapFromList(optDecls []*tsoptions.CommandLineOption) *tsoptions.NameMap
//go:linkname GetOptionsSyntaxByArrayElementValue github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetOptionsSyntaxByArrayElementValue
func GetOptionsSyntaxByArrayElementValue(objectLiteral *ast.ObjectLiteralExpression, propKey string, elementValue string) *ast.Node
//go:linkname GetParsedCommandLineOfConfigFile github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetParsedCommandLineOfConfigFile
func GetParsedCommandLineOfConfigFile(configFileName string, options *core.CompilerOptions, optionsRaw *collections.OrderedMap[string, any], sys tsoptions.ParseConfigHost, extendedConfigCache tsoptions.ExtendedConfigCache) (*tsoptions.ParsedCommandLine, []*ast.Diagnostic)
//go:linkname GetParsedCommandLineOfConfigFilePath github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetParsedCommandLineOfConfigFilePath
func GetParsedCommandLineOfConfigFilePath(configFileName string, path tspath.Path, options *core.CompilerOptions, optionsRaw *collections.OrderedMap[string, any], sys tsoptions.ParseConfigHost, extendedConfigCache tsoptions.ExtendedConfigCache) (*tsoptions.ParsedCommandLine, []*ast.Diagnostic)
//go:linkname GetSupportedExtensionsWithJsonIfResolveJsonModule github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetSupportedExtensionsWithJsonIfResolveJsonModule
func GetSupportedExtensionsWithJsonIfResolveJsonModule(compilerOptions *core.CompilerOptions, supportedExtensions [][]string) [][]string
//go:linkname GetTsConfigPropArrayElementValue github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.GetTsConfigPropArrayElementValue
func GetTsConfigPropArrayElementValue(tsConfigSourceFile *ast.SourceFile, propKey string, elementValue string) *ast.StringLiteral
var InverseJsxOptionMap = tsoptions.InverseJsxOptionMap
var LibFilesSet = tsoptions.LibFilesSet
var LibMap = tsoptions.LibMap
var Libs = tsoptions.Libs
type NameMap = tsoptions.NameMap
//go:linkname NewParsedCommandLine github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.NewParsedCommandLine
func NewParsedCommandLine(compilerOptions *core.CompilerOptions, rootFileNames []string, comparePathsOptions tspath.ComparePathsOptions) *tsoptions.ParsedCommandLine
//go:linkname NewTsconfigSourceFileFromFilePath github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.NewTsconfigSourceFileFromFilePath
func NewTsconfigSourceFileFromFilePath(configFileName string, configPath tspath.Path, configSourceText string) *tsoptions.TsConfigSourceFile
var OptionsDeclarations = tsoptions.OptionsDeclarations
var OptionsForBuild = tsoptions.OptionsForBuild
var OptionsForWatch = tsoptions.OptionsForWatch
//go:linkname ParseBuildCommandLine github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseBuildCommandLine
func ParseBuildCommandLine(commandLine []string, host tsoptions.ParseConfigHost) *tsoptions.ParsedBuildCommandLine
//go:linkname ParseBuildOptions github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseBuildOptions
func ParseBuildOptions(key string, value any, allOptions *core.BuildOptions) []*ast.Diagnostic
//go:linkname ParseCommandLine github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseCommandLine
func ParseCommandLine(commandLine []string, host tsoptions.ParseConfigHost) *tsoptions.ParsedCommandLine
type ParseCommandLineWorkerDiagnostics = tsoptions.ParseCommandLineWorkerDiagnostics
//go:linkname ParseCompilerOptions github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseCompilerOptions
func ParseCompilerOptions(key string, value any, allOptions *core.CompilerOptions) []*ast.Diagnostic
//go:linkname ParseConfigFileTextToJson github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseConfigFileTextToJson
func ParseConfigFileTextToJson(fileName string, path tspath.Path, jsonText string) (any, []*ast.Diagnostic)
type ParseConfigHost = tsoptions.ParseConfigHost
//go:linkname ParseExtendedConfig github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseExtendedConfig
func ParseExtendedConfig(fileName string, path tspath.Path, resolutionStack []string, host tsoptions.ParseConfigHost, extendedConfigCache tsoptions.ExtendedConfigCache) *tsoptions.ExtendedConfigCacheEntry
//go:linkname ParseListTypeOption github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseListTypeOption
func ParseListTypeOption(opt *tsoptions.CommandLineOption, value string) ([]any, []*ast.Diagnostic)
//go:linkname ParseString github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseString
func ParseString(value any) string
//go:linkname ParseStringArray github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseStringArray
func ParseStringArray(value any) []string
//go:linkname ParseTristate github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseTristate
func ParseTristate(value any) core.Tristate
//go:linkname ParseTypeAcquisition github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseTypeAcquisition
func ParseTypeAcquisition(key string, value any, allOptions *core.TypeAcquisition) []*ast.Diagnostic
//go:linkname ParseWatchOptions github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.ParseWatchOptions
func ParseWatchOptions(key string, value any, allOptions *core.WatchOptions) []*ast.Diagnostic
type ParsedBuildCommandLine = tsoptions.ParsedBuildCommandLine
type ParsedCommandLine = tsoptions.ParsedCommandLine
type SourceOutputAndProjectReference = tsoptions.SourceOutputAndProjectReference
//go:linkname TargetToLibMap github.com/i2y/ramune/internal/rslint/tsgo_pinned/tsoptions.TargetToLibMap
func TargetToLibMap() map[core.ScriptTarget]string
type TsConfigSourceFile = tsoptions.TsConfigSourceFile
var TscBuildOption = tsoptions.TscBuildOption
var WatchNameMap = tsoptions.WatchNameMap
