// Code generated by tools/gen_shims. DO NOT EDIT.

package scanner

import "github.com/i2y/ramune/internal/tsgo/ast"
import "github.com/i2y/ramune/internal/tsgo/core"
import "github.com/i2y/ramune/internal/tsgo/scanner"
import "iter"
import _ "unsafe"

//go:linkname ComputeLineOfPosition github.com/i2y/ramune/internal/tsgo/scanner.ComputeLineOfPosition
func ComputeLineOfPosition(lineStarts []core.TextPos, pos int) int

//go:linkname ComputePositionOfLineAndByteOffset github.com/i2y/ramune/internal/tsgo/scanner.ComputePositionOfLineAndByteOffset
func ComputePositionOfLineAndByteOffset(lineStarts []core.TextPos, line int, byteOffset int) int

//go:linkname ComputePositionOfLineAndUTF16Character github.com/i2y/ramune/internal/tsgo/scanner.ComputePositionOfLineAndUTF16Character
func ComputePositionOfLineAndUTF16Character(lineStarts []core.TextPos, line int, character core.UTF16Offset, text string, allowEdits bool) int

//go:linkname DeclarationNameToString github.com/i2y/ramune/internal/tsgo/scanner.DeclarationNameToString
func DeclarationNameToString(name *ast.Node) string

type ErrorCallback = scanner.ErrorCallback
type EscapeSequenceScanningFlags = scanner.EscapeSequenceScanningFlags

const EscapeSequenceScanningFlagsAllowExtendedUnicodeEscape = scanner.EscapeSequenceScanningFlagsAllowExtendedUnicodeEscape
const EscapeSequenceScanningFlagsAnnexB = scanner.EscapeSequenceScanningFlagsAnnexB
const EscapeSequenceScanningFlagsAnyUnicodeMode = scanner.EscapeSequenceScanningFlagsAnyUnicodeMode
const EscapeSequenceScanningFlagsAtomEscape = scanner.EscapeSequenceScanningFlagsAtomEscape
const EscapeSequenceScanningFlagsRegularExpression = scanner.EscapeSequenceScanningFlagsRegularExpression
const EscapeSequenceScanningFlagsReportErrors = scanner.EscapeSequenceScanningFlagsReportErrors
const EscapeSequenceScanningFlagsReportInvalidEscapeErrors = scanner.EscapeSequenceScanningFlagsReportInvalidEscapeErrors
const EscapeSequenceScanningFlagsString = scanner.EscapeSequenceScanningFlagsString

//go:linkname GetECMAEndLinePosition github.com/i2y/ramune/internal/tsgo/scanner.GetECMAEndLinePosition
func GetECMAEndLinePosition(sourceFile *ast.SourceFile, line int) int

//go:linkname GetECMALineAndByteOffsetOfPosition github.com/i2y/ramune/internal/tsgo/scanner.GetECMALineAndByteOffsetOfPosition
func GetECMALineAndByteOffsetOfPosition(sourceFile ast.SourceFileLike, pos int) (line int, byteOffset int)

//go:linkname GetECMALineAndUTF16CharacterOfPosition github.com/i2y/ramune/internal/tsgo/scanner.GetECMALineAndUTF16CharacterOfPosition
func GetECMALineAndUTF16CharacterOfPosition(sourceFile ast.SourceFileLike, pos int) (line int, character core.UTF16Offset)

//go:linkname GetECMALineOfPosition github.com/i2y/ramune/internal/tsgo/scanner.GetECMALineOfPosition
func GetECMALineOfPosition(sourceFile ast.SourceFileLike, pos int) int

//go:linkname GetECMALineStarts github.com/i2y/ramune/internal/tsgo/scanner.GetECMALineStarts
func GetECMALineStarts(sourceFile ast.SourceFileLike) []core.TextPos

//go:linkname GetECMAPositionOfLineAndByteOffset github.com/i2y/ramune/internal/tsgo/scanner.GetECMAPositionOfLineAndByteOffset
func GetECMAPositionOfLineAndByteOffset(sourceFile ast.SourceFileLike, line int, byteOffset int) int

//go:linkname GetECMAPositionOfLineAndUTF16Character github.com/i2y/ramune/internal/tsgo/scanner.GetECMAPositionOfLineAndUTF16Character
func GetECMAPositionOfLineAndUTF16Character(sourceFile ast.SourceFileLike, line int, character core.UTF16Offset) int

//go:linkname GetErrorRangeForNode github.com/i2y/ramune/internal/tsgo/scanner.GetErrorRangeForNode
func GetErrorRangeForNode(sourceFile *ast.SourceFile, node *ast.Node) core.TextRange

//go:linkname GetIdentifierToken github.com/i2y/ramune/internal/tsgo/scanner.GetIdentifierToken
func GetIdentifierToken(str string) ast.Kind

//go:linkname GetLeadingCommentRanges github.com/i2y/ramune/internal/tsgo/scanner.GetLeadingCommentRanges
func GetLeadingCommentRanges(f *ast.NodeFactory, text string, pos int) iter.Seq[ast.CommentRange]

//go:linkname GetRangeOfTokenAtPosition github.com/i2y/ramune/internal/tsgo/scanner.GetRangeOfTokenAtPosition
func GetRangeOfTokenAtPosition(sourceFile *ast.SourceFile, pos int) core.TextRange

//go:linkname GetScannerForSourceFile github.com/i2y/ramune/internal/tsgo/scanner.GetScannerForSourceFile
func GetScannerForSourceFile(sourceFile *ast.SourceFile, pos int) *scanner.Scanner

//go:linkname GetShebang github.com/i2y/ramune/internal/tsgo/scanner.GetShebang
func GetShebang(text string) string

//go:linkname GetSourceTextOfNodeFromSourceFile github.com/i2y/ramune/internal/tsgo/scanner.GetSourceTextOfNodeFromSourceFile
func GetSourceTextOfNodeFromSourceFile(sourceFile *ast.SourceFile, node *ast.Node, includeTrivia bool) string

//go:linkname GetTextOfNode github.com/i2y/ramune/internal/tsgo/scanner.GetTextOfNode
func GetTextOfNode(node *ast.Node) string

//go:linkname GetTextOfNodeFromSourceText github.com/i2y/ramune/internal/tsgo/scanner.GetTextOfNodeFromSourceText
func GetTextOfNodeFromSourceText(sourceText string, node *ast.Node, includeTrivia bool) string

//go:linkname GetTokenPosOfNode github.com/i2y/ramune/internal/tsgo/scanner.GetTokenPosOfNode
func GetTokenPosOfNode(node *ast.Node, sourceFile *ast.SourceFile, includeJSDoc bool) int

//go:linkname GetTrailingCommentRanges github.com/i2y/ramune/internal/tsgo/scanner.GetTrailingCommentRanges
func GetTrailingCommentRanges(f *ast.NodeFactory, text string, pos int) iter.Seq[ast.CommentRange]

//go:linkname GetViableKeywordSuggestions github.com/i2y/ramune/internal/tsgo/scanner.GetViableKeywordSuggestions
func GetViableKeywordSuggestions() []string

//go:linkname IdentifierToKeywordKind github.com/i2y/ramune/internal/tsgo/scanner.IdentifierToKeywordKind
func IdentifierToKeywordKind(node *ast.Identifier) ast.Kind

//go:linkname IsIdentifierPart github.com/i2y/ramune/internal/tsgo/scanner.IsIdentifierPart
func IsIdentifierPart(ch rune) bool

//go:linkname IsIdentifierPartEx github.com/i2y/ramune/internal/tsgo/scanner.IsIdentifierPartEx
func IsIdentifierPartEx(ch rune, languageVariant core.LanguageVariant) bool

//go:linkname IsIdentifierStart github.com/i2y/ramune/internal/tsgo/scanner.IsIdentifierStart
func IsIdentifierStart(ch rune) bool

//go:linkname IsIdentifierText github.com/i2y/ramune/internal/tsgo/scanner.IsIdentifierText
func IsIdentifierText(name string, languageVariant core.LanguageVariant) bool

//go:linkname IsIntrinsicJsxName github.com/i2y/ramune/internal/tsgo/scanner.IsIntrinsicJsxName
func IsIntrinsicJsxName(name string) bool

//go:linkname IsValidIdentifier github.com/i2y/ramune/internal/tsgo/scanner.IsValidIdentifier
func IsValidIdentifier(s string) bool

//go:linkname NewScanner github.com/i2y/ramune/internal/tsgo/scanner.NewScanner
func NewScanner() *scanner.Scanner

//go:linkname ScanTokenAtPosition github.com/i2y/ramune/internal/tsgo/scanner.ScanTokenAtPosition
func ScanTokenAtPosition(sourceFile *ast.SourceFile, pos int) ast.Kind

type Scanner = scanner.Scanner
type ScannerState = scanner.ScannerState

//go:linkname SkipTrivia github.com/i2y/ramune/internal/tsgo/scanner.SkipTrivia
func SkipTrivia(text string, pos int) int

//go:linkname SkipTriviaEx github.com/i2y/ramune/internal/tsgo/scanner.SkipTriviaEx
func SkipTriviaEx(text string, pos int, options *scanner.SkipTriviaOptions) int

type SkipTriviaOptions = scanner.SkipTriviaOptions

//go:linkname StringToToken github.com/i2y/ramune/internal/tsgo/scanner.StringToToken
func StringToToken(s string) ast.Kind

//go:linkname TokenToString github.com/i2y/ramune/internal/tsgo/scanner.TokenToString
func TokenToString(token ast.Kind) string
