package gotranspiler

import (
	"fmt"
	"go/importer"
	"go/token"
	"go/types"
	"strings"
)

// TypeGenerator generates TypeScript .d.ts declarations from Go packages.
type TypeGenerator struct {
	fset       *token.FileSet
	imp        types.Importer
	buf        strings.Builder
	emitted    map[string]bool
	targetPkgs map[string]bool
	currentPkg string
}

// GenerateDTS generates TypeScript .d.ts content for the given Go packages.
// Package names can optionally have a "go:" prefix (e.g., "go:fmt" or "fmt").
func GenerateDTS(packages []string) (string, error) {
	fset := token.NewFileSet()
	g := &TypeGenerator{
		fset:       fset,
		imp:        importer.ForCompiler(fset, "gc", nil),
		emitted:    make(map[string]bool),
		targetPkgs: make(map[string]bool),
	}

	paths := make([]string, len(packages))
	for i, p := range packages {
		paths[i] = strings.TrimPrefix(p, "go:")
		g.targetPkgs[paths[i]] = true
	}

	g.buf.WriteString("// Generated by ramune typegen — do not edit\n")

	for _, pkgPath := range paths {
		pkg, err := g.imp.Import(pkgPath)
		if err != nil {
			return "", fmt.Errorf("loading %s: %w", pkgPath, err)
		}
		g.emitPackage(pkgPath, pkg)
	}

	return g.buf.String(), nil
}

func (g *TypeGenerator) emitPackage(pkgPath string, pkg *types.Package) {
	g.currentPkg = pkgPath
	fmt.Fprintf(&g.buf, "\ndeclare module \"go:%s\" {\n", pkgPath)

	scope := pkg.Scope()
	names := scope.Names()

	var typeNames []*types.TypeName
	var funcs []*types.Func
	var consts []*types.Const
	var vars []*types.Var

	for _, name := range names {
		obj := scope.Lookup(name)
		if !obj.Exported() {
			continue
		}
		switch o := obj.(type) {
		case *types.TypeName:
			typeNames = append(typeNames, o)
		case *types.Func:
			funcs = append(funcs, o)
		case *types.Const:
			consts = append(consts, o)
		case *types.Var:
			vars = append(vars, o)
		}
	}

	for _, tn := range typeNames {
		g.emitTypeName(tn)
	}
	for _, c := range consts {
		g.emitConst(c)
	}
	for _, v := range vars {
		g.emitVar(v)
	}
	for _, f := range funcs {
		g.emitFunc(f)
	}

	g.buf.WriteString("}\n")
}

func (g *TypeGenerator) emitTypeName(tn *types.TypeName) {
	name := tn.Name()
	key := g.currentPkg + "." + name
	if g.emitted[key] {
		return
	}
	g.emitted[key] = true

	named, ok := tn.Type().(*types.Named)
	if !ok {
		fmt.Fprintf(&g.buf, "  export type %s = %s;\n", name, g.goTypeToTS(tn.Type().Underlying()))
		return
	}

	switch u := named.Underlying().(type) {
	case *types.Struct:
		g.emitStructInterface(name, named, u)
	case *types.Interface:
		g.emitInterfaceDecl(name, u)
	default:
		fmt.Fprintf(&g.buf, "  export type %s = %s;\n", name, g.goTypeToTS(named.Underlying()))
	}
}

func (g *TypeGenerator) emitStructInterface(name string, named *types.Named, s *types.Struct) {
	fmt.Fprintf(&g.buf, "  export interface %s {\n", name)

	for i := range s.NumFields() {
		f := s.Field(i)
		if !f.Exported() {
			continue
		}
		fmt.Fprintf(&g.buf, "    %s: %s;\n", f.Name(), g.goTypeToTS(f.Type()))
	}

	for i := range named.NumMethods() {
		m := named.Method(i)
		if !m.Exported() {
			continue
		}
		sig := m.Type().(*types.Signature)
		fmt.Fprintf(&g.buf, "    %s%s;\n", m.Name(), g.funcSignatureToTS(sig))
	}

	g.buf.WriteString("  }\n")
}

func (g *TypeGenerator) emitInterfaceDecl(name string, iface *types.Interface) {
	if iface.NumMethods() == 0 {
		fmt.Fprintf(&g.buf, "  export type %s = any;\n", name)
		return
	}

	fmt.Fprintf(&g.buf, "  export interface %s {\n", name)
	for i := range iface.NumMethods() {
		m := iface.Method(i)
		if !m.Exported() {
			continue
		}
		sig := m.Type().(*types.Signature)
		fmt.Fprintf(&g.buf, "    %s%s;\n", m.Name(), g.funcSignatureToTS(sig))
	}
	g.buf.WriteString("  }\n")
}

func (g *TypeGenerator) emitConst(c *types.Const) {
	fmt.Fprintf(&g.buf, "  export const %s: %s;\n", c.Name(), g.goTypeToTS(c.Type()))
}

func (g *TypeGenerator) emitVar(v *types.Var) {
	fmt.Fprintf(&g.buf, "  export const %s: %s;\n", v.Name(), g.goTypeToTS(v.Type()))
}

func (g *TypeGenerator) emitFunc(f *types.Func) {
	sig := f.Type().(*types.Signature)
	fmt.Fprintf(&g.buf, "  export function %s%s;\n", f.Name(), g.funcSignatureToTS(sig))
}

func (g *TypeGenerator) funcSignatureToTS(sig *types.Signature) string {
	var b strings.Builder
	b.WriteString("(")
	g.writeParams(&b, sig)
	b.WriteString("): ")
	b.WriteString(g.returnTypeToTS(sig.Results()))
	return b.String()
}

func (g *TypeGenerator) writeParams(b *strings.Builder, sig *types.Signature) {
	params := sig.Params()
	variadic := sig.Variadic()
	n := params.Len()

	for i := range n {
		if i > 0 {
			b.WriteString(", ")
		}
		p := params.At(i)
		name := p.Name()
		if name == "" {
			name = fmt.Sprintf("arg%d", i)
		}

		if i == n-1 && variadic {
			sliceType, ok := p.Type().(*types.Slice)
			if ok {
				fmt.Fprintf(b, "...%s: %s[]", name, g.goTypeToTS(sliceType.Elem()))
			} else {
				fmt.Fprintf(b, "...%s: any[]", name)
			}
		} else {
			fmt.Fprintf(b, "%s: %s", name, g.goTypeToTS(p.Type()))
		}
	}
}

func (g *TypeGenerator) returnTypeToTS(results *types.Tuple) string {
	if results == nil || results.Len() == 0 {
		return "void"
	}

	if results.Len() == 1 {
		return g.goTypeToTS(results.At(0).Type())
	}

	var parts []string
	for i := range results.Len() {
		parts = append(parts, g.goTypeToTS(results.At(i).Type()))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func (g *TypeGenerator) goTypeToTS(t types.Type) string {
	switch t := t.(type) {
	case *types.Named:
		return g.namedTypeToTS(t)

	case *types.Basic:
		return g.basicTypeToTS(t)

	case *types.Slice:
		return g.arrayLikeToTS(t.Elem())

	case *types.Array:
		return g.arrayLikeToTS(t.Elem())

	case *types.Map:
		return fmt.Sprintf("Record<%s, %s>", g.goTypeToTS(t.Key()), g.goTypeToTS(t.Elem()))

	case *types.Pointer:
		return g.goTypeToTS(t.Elem())

	case *types.Interface:
		if t.Empty() {
			return "any"
		}
		var methods []string
		for i := range t.NumMethods() {
			m := t.Method(i)
			sig := m.Type().(*types.Signature)
			methods = append(methods, fmt.Sprintf("%s%s", m.Name(), g.funcSignatureToTS(sig)))
		}
		return "{ " + strings.Join(methods, "; ") + " }"

	case *types.Signature:
		return g.funcTypeToTS(t)

	case *types.Chan:
		return "any"

	case *types.Struct:
		if t.NumFields() == 0 {
			return "{}"
		}
		var fields []string
		for i := range t.NumFields() {
			f := t.Field(i)
			if f.Exported() {
				fields = append(fields, fmt.Sprintf("%s: %s", f.Name(), g.goTypeToTS(f.Type())))
			}
		}
		return "{ " + strings.Join(fields, "; ") + " }"

	case *types.TypeParam:
		return "any"

	default:
		return "any"
	}
}

func (g *TypeGenerator) arrayLikeToTS(elem types.Type) string {
	ts := g.goTypeToTS(elem)
	if strings.ContainsAny(ts, " |") {
		return "(" + ts + ")[]"
	}
	return ts + "[]"
}

func (g *TypeGenerator) namedTypeToTS(t *types.Named) string {
	obj := t.Obj()

	if obj.Pkg() == nil {
		switch obj.Name() {
		case "error":
			return "Error | null"
		case "byte", "rune":
			return "number"
		case "bool":
			return "boolean"
		case "string":
			return "string"
		case "any":
			return "any"
		}
	}

	name := obj.Name()
	pkg := obj.Pkg()

	if pkg != nil {
		pkgPath := pkg.Path()
		if pkgPath == g.currentPkg {
			return name
		}
		if g.targetPkgs[pkgPath] {
			return fmt.Sprintf("import('go:%s').%s", pkgPath, name)
		}
		return g.fallbackNamedType(t)
	}

	return name
}

func (g *TypeGenerator) fallbackNamedType(t *types.Named) string {
	if u, ok := t.Underlying().(*types.Basic); ok {
		return g.basicTypeToTS(u)
	}
	return "any"
}

func (g *TypeGenerator) basicTypeToTS(t *types.Basic) string {
	switch t.Kind() {
	case types.Bool, types.UntypedBool:
		return "boolean"
	case types.String, types.UntypedString:
		return "string"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64,
		types.Uintptr, types.UntypedInt, types.UntypedFloat, types.UntypedRune:
		return "number"
	case types.UnsafePointer:
		return "number"
	case types.UntypedNil:
		return "null"
	default:
		return "any"
	}
}

func (g *TypeGenerator) funcTypeToTS(sig *types.Signature) string {
	var b strings.Builder
	b.WriteString("(")
	g.writeParams(&b, sig)
	b.WriteString(") => ")
	b.WriteString(g.returnTypeToTS(sig.Results()))
	return b.String()
}
