package gotranspiler

import (
	"strings"
	"testing"
)

func TestGenerateDTS_Fmt(t *testing.T) {
	out, err := GenerateDTS([]string{"go:fmt"})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("output:\n%s", out)

	// Module declaration
	if !strings.Contains(out, `declare module "go:fmt"`) {
		t.Error("expected declare module for go:fmt")
	}

	// Println: variadic, returns (int, error)
	if !strings.Contains(out, "export function Println(") {
		t.Error("expected Println")
	}
	if !strings.Contains(out, "...a: any[]") {
		t.Error("expected variadic ...a: any[]")
	}
	// Multi-return [number, Error | null]
	if !strings.Contains(out, "[number, Error | null]") {
		t.Error("expected [number, Error | null] return type")
	}

	// Sprintf: returns string
	if !strings.Contains(out, "export function Sprintf(") {
		t.Error("expected Sprintf")
	}
	if !strings.Contains(out, "): string") {
		t.Error("expected string return type for Sprintf")
	}

	// Stringer interface
	if !strings.Contains(out, "export interface Stringer") {
		t.Error("expected Stringer interface")
	}
}

func TestGenerateDTS_Strings(t *testing.T) {
	out, err := GenerateDTS([]string{"strings"})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("output:\n%s", out)

	if !strings.Contains(out, `declare module "go:strings"`) {
		t.Error("expected declare module for go:strings")
	}

	// Contains(s, substr string) bool → (s: string, substr: string): boolean
	if !strings.Contains(out, "export function Contains(") {
		t.Error("expected Contains function")
	}
	if !strings.Contains(out, "): boolean") {
		t.Error("expected boolean return type for Contains")
	}

	// Replace returns string
	if !strings.Contains(out, "export function Replace(") {
		t.Error("expected Replace function")
	}
}

func TestGenerateDTS_NetHttp(t *testing.T) {
	out, err := GenerateDTS([]string{"net/http"})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("output (first 2000 chars):\n%.2000s", out)

	if !strings.Contains(out, `declare module "go:net/http"`) {
		t.Error("expected declare module for go:net/http")
	}

	// Response struct as interface
	if !strings.Contains(out, "export interface Response") {
		t.Error("expected Response interface")
	}
	if !strings.Contains(out, "StatusCode: number") {
		t.Error("expected StatusCode field")
	}

	// Get function with multi-return
	if !strings.Contains(out, "export function Get(") {
		t.Error("expected Get function")
	}

	// ListenAndServe
	if !strings.Contains(out, "export function ListenAndServe(") {
		t.Error("expected ListenAndServe function")
	}
}

func TestGenerateDTS_MultiPackage(t *testing.T) {
	out, err := GenerateDTS([]string{"go:fmt", "go:strings"})
	if err != nil {
		t.Fatal(err)
	}

	fmtCount := strings.Count(out, `declare module "go:fmt"`)
	stringsCount := strings.Count(out, `declare module "go:strings"`)
	if fmtCount != 1 {
		t.Errorf("expected 1 fmt module, got %d", fmtCount)
	}
	if stringsCount != 1 {
		t.Errorf("expected 1 strings module, got %d", stringsCount)
	}
}

func TestGenerateDTS_GoPrefix(t *testing.T) {
	// go:fmt and fmt should produce identical output
	out1, err := GenerateDTS([]string{"go:fmt"})
	if err != nil {
		t.Fatal(err)
	}
	out2, err := GenerateDTS([]string{"fmt"})
	if err != nil {
		t.Fatal(err)
	}
	if out1 != out2 {
		t.Error("go:fmt and fmt should produce identical output")
	}
}

func TestGenerateDTS_Header(t *testing.T) {
	out, err := GenerateDTS([]string{"fmt"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(out, "// Generated by ramune typegen") {
		t.Error("expected header comment")
	}
}
